on: push
permissions:
  contents: write

jobs:
  build:
    name: 打包
    runs-on: windows-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: 安装依赖
        run: npm install

      - name: 构建
        run: npm run build

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: EA-WRC_Club-Manager.exe
          path: release/**/*.exe